const TodosActionTypes = {
  PENDING: "REQUEST_TODOS_PENDING",
  SUCCESS: "REQUEST_TODOS_SUCCESS",
  FAILED: "REQUEST_TODOS_FAILED",

  ADD_TASK: "ADD_TASK",
  REMOVE_TASK: "REMOVE_TASK",
  TOGGLE_COMPLETED: "TOGGLE_COMPLETED",

  ADD_TASK_ASYNC: "ADD_TASK_ASYNC",
  REMOVE_TASK_ASYNC: "REMOVE_TASK_ASYNC",
  TOGGLE_COMPLETED_ASYNC: "TOGGLE_COMPLETED_ASYNC",
};

export default TodosActionTypes;
